force-app/main/default/objects/Showroom__c/Showroom__c.object-meta.xml
<CustomObject>
    <label>Showroom</label>
    <nameField>
        <label>Car Showroom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Firma, do której należy salon</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Salony</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Serial number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Brands__c.field-meta.xml
<CustomField>
    <fullName>Brands__c</fullName>
    <label>Brand</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Showroom__c.field-meta.xml
<CustomField>
    <fullName>Showroom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A showroom where the vehicle is physically available.</description>
    <label>Showroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Showroom__c/Vehicle_Showroom__c.object-meta.xml
<CustomObject>
    <label>Vehicle Showroom</label>
    <nameField>
        <label>Vehicle Showroom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Showroom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Showroom__c/fields/CarShowrooms__c.field-meta.xml
<CustomField>
    <fullName>CarShowrooms__c</fullName>
    <label>CarShowroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipName>Vehicle_Showroom_Juction_Objects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Showroom__c/fields/Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Vehicles__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipName>Vehicle_Showroom_Juction_Objects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AccountShowroomVehicleBrowserController.cls
/**
 * @author Adrianna Zajac <adrianna.zajac@accenture.com>
 * @date 25/03/2024
 * @description This class provides methods for getting data: account, showrroms, vehocles.
 */
public with sharing class AccountShowroomVehicleBrowserController {
    /**
     * @author Adrianna Zajac <adrianna.zajac@accenture.com>
     * @date 25/03/2024
     * @description The method returns list of all accounts.
     */
    @AuraEnabled(cacheable=true)
    public static Account[] getAllAccounts() {
        return [
            SELECT Name
            FROM Account
            ORDER BY Name
        ];
    }
     /**
     * @author Adrianna Zajac <adrianna.zajac@accenture.com>
     * @date 25/03/2024
     * @description The method returns list of showrooms which are connected with accountId.
     * 
     * @param accountId Id of account for which method will return list of showrooms.
     */
    @AuraEnabled(cacheable=true)
    public static Showroom__c[] getShowroomsByAccountId(Id accountId) {
        return [
            SELECT Name
            FROM Showroom__c
            WHERE Account__c = :accountId
            ORDER BY Name
        ];
    }
    /**
     * @author Adrianna Zajac <adrianna.zajac@accenture.com>
     * @date 16/03/2024
     * @description The method returns list of vehicles which are connected with showroomId.
     * 
     * @param showroomId Id of showroom for which method will return list of vehicles.
     */
    @AuraEnabled(cacheable=true)
    public static Vehicle__c[] getVehiclesByShowroomId(Id showroomId) {
        List<Id> vehiclesId = new List<Id>();
        List<Vehicle_Showroom__c> vehicleShowrooms = [SELECT Vehicles__c FROM Vehicle_Showroom__c
        WHERE CarShowrooms__c = :showroomId];
        for(Vehicle_Showroom__c vehicleShowroom : vehicleShowrooms){
            vehiclesId.add(vehicleShowroom.Vehicles__c);
        }
        List<Vehicle__c> vehicles = [
            SELECT Name, Brands__c, Model__c
            FROM Vehicle__c
            WHERE Id IN :vehiclesId
            ORDER BY Brands__c
        ];
        return vehicles;
    }
}