force-app/main/default/objects/Showroom__c/Showroom__c.object-meta.xml
<CustomObject>
    <label>Showroom</label>
    <nameField>
        <label>Car Showroom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Firma, do której należy salon</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Salony</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Showroom__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Jakiego rodzaju salon ten posiada samochody?</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cars</fullName>
            </value>
            <value>
                <fullName>Specialized cars</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Telemetry__c/Telemetry__c.object-meta.xml
<CustomObject>
    <label>Telemetry</label>
    <nameField>
        <label>Telemetry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Telemetry</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Telemetry__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>piston</fullName>
            </value>
            <value>
                <fullName>brake disc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Telemetry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>temperature</fullName>
            </value>
            <value>
                <fullName>rotational speed</fullName>
            </value>
            <value>
                <fullName>force</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Telemetry__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Telemetry</relationshipLabel>
    <relationshipName>Telemetry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Serial number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Brands__c.field-meta.xml
<CustomField>
    <fullName>Brands__c</fullName>
    <label>Brand</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Showroom__c.field-meta.xml
<CustomField>
    <fullName>Showroom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A showroom where the vehicle is physically available.</description>
    <label>Showroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Type of car</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sportowe</fullName>
            </value>
            <value>
                <fullName>Rodzinne</fullName>
            </value>
            <value>
                <fullName>Dostawcze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Showroom__c/Vehicle_Showroom__c.object-meta.xml
<CustomObject>
    <label>Vehicle Showroom</label>
    <nameField>
        <label>Vehicle Showroom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Showroom</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Showroom__c/fields/CarShowrooms__c.field-meta.xml
<CustomField>
    <fullName>CarShowrooms__c</fullName>
    <label>CarShowroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipName>Vehicle_Showroom_Juction_Objects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Showroom__c/fields/Is_available_in_showroom__c.field-meta.xml
<CustomField>
    <fullName>Is_available_in_showroom__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is available in showroom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle_Showroom__c/fields/Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Vehicles__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipName>Vehicle_Showroom_Juction_Objects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
	public static List<Vehicle__c> createVehicles(Integer numVehicles) {
        List<Vehicle__c> vehicles = new List<Vehicle__c>();
        for(Integer i=0;i<numVehicles;i++) {
            Vehicle__c vehicle = new Vehicle__c(
                Name = '1122334455'+i,
                Brands__c = 'Suzuki'+i,
                Model__c = 'Vitara'+i,
                Production_Year__c = 2018
            );
            vehicles.add(vehicle);
        }
        insert vehicles;
        return vehicles;
    }
    
    public static List<Showroom__c> createShowrooms(Integer numShowrooms){
        List<Showroom__c> showrooms = new List<Showroom__c>();
        for(Integer i=0;i<numShowrooms;i++) {
            Showroom__c showroom = new Showroom__c(
                Name = 'Salon Suzuki Warszawa'+i,
                Account__c = '001Qy00000DREyhIAH',
                Type__c = 'Cars'
        	); 
            showrooms.add(showroom);
        }
        insert showrooms;
        return showrooms;
    }
    
     public static List<Vehicle_Showroom__c> createVehiclesShowrooms(Integer numVehiclesShowrooms){
        List<Showroom__c> showrooms = createShowrooms(numVehiclesShowrooms);
        List<Vehicle__c> vehicles = createVehicles(numVehiclesShowrooms);
        List<Vehicle_Showroom__c> vehicleShowrooms = new List<Vehicle_Showroom__c>(); 
         
        for(Integer i=0; i<numVehiclesShowrooms; i++) {
            Vehicle_Showroom__c vehicleShowroom = new Vehicle_Showroom__c(
                Vehicles__c = vehicles[i].Id,
                CarShowrooms__c = showrooms[i].Id,
                Is_available_in_showroom__c = false
        	); 
            vehicleShowrooms.add(vehicleShowroom);
        }         
        return vehicleShowrooms;
    }
    
    public static List<Telemetry__c> createTelemetries(Integer numTelemetries) {
        List<Telemetry__c> telemetries = new List<Telemetry__c>();
        for(Integer i=0;i<numTelemetries;i++) {
            Telemetry__c telemetry = new Telemetry__c(
                Name = 'Telemetry'+i,
                Component__c = 'piston',
                Type__c = 'temperature'
            );
            telemetries.add(telemetry);
        }
        insert telemetries;
        return telemetries;
    }  
}